run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/coredds/ChronoGo)
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/coredds/ChronoGo
  govet:
    shadow: true
  lll:
    line-length: 140
  misspell:
    locale: US
  revive:
    min-confidence: 0
  funlen:
    lines: 80
    statements: 50
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/coredds/ChronoGo"
            desc: "Use relative imports instead"
        files:
          - "!**/*_test.go"
          - "!**/example_test.go"
          - "!**/cmd/**"

linters:
  enable:
    - errcheck
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disable:
    - gci
    - godot
    - goconst
    - gocritic
    - lll
    - misspell
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - goconst
        - lll
    - path: cmd/
      linters:
        - gochecknoinits
        - funlen
        - gocognit
        - lll
        - depguard
    - path: example_test\.go
      linters:
        - depguard
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
