run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/coredds/ChronoGo)
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/coredds/ChronoGo
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
  revive:
    min-confidence: 0

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  disable:
    - gochecknoglobals
    - goerr113
    - golint
    - maligned
    - prealloc
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gomnd
        - dupl
    - path: cmd/
      linters:
        - gochecknoinits
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
