theme: jekyll-theme-minimal
title: chronogo
description: A powerful and elegant Go datetime library inspired by Python's Pendulum
show_downloads: true
github:
  repository_url: https://github.com/coredds/chronogo
